[package]
name = "multiarray"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
meta_programming = { git = "https://github.com/fuookami/rust-meta-programming.git" }
